In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
a + 2

array([3, 4, 5, 6])

In [4]:
a += 2

In [5]:
print(a)

[3 4 5 6]


In [7]:
b = np.array([1,0,1,0])

In [8]:
a+b

array([4, 4, 6, 6])

In [9]:
a ** 2

array([ 9, 16, 25, 36])

In [12]:
# Take the sin, cos, tan

print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[-0.9899925  -0.65364362  0.28366219  0.96017029]
[-0.14254654  1.15782128 -3.38051501 -0.29100619]


#### Linear Algebra

In [15]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [17]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [18]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [19]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
print(np.min(stats))
print(np.max(stats, axis=1))

1
[3 6]


#### Re-organizing arrays

In [24]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [26]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [27]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
# Horizontal stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### Miscellaneous

In [35]:
filedata = np.genfromtxt('data.txt', delimiter=",")
filedata.astype('int32')
print(filedata)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   5.   6.   7.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.  78.   0.   1.   2.   3.   9.   8.
    7.   1.  76.  88.]]


#### Boolean Masking and Advanced indexing

In [37]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False,  True, False,
        False, False, False, False, False, False, False,  True,  True]])

In [38]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [41]:
## You can index with a list in numpy
a = np.array([100,200,300,400,500,600,700,800,900])

a[[1,2,8]]

array([200, 300, 900])

In [42]:
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True, False,
       False, False, False, False, False, False, False,  True,  True])

In [44]:
np.all(filedata > 50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [45]:
np.any(filedata > 50, axis = 1)

array([ True,  True,  True])

In [47]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False,  True, False,
        False, False, False, False, False, False, False,  True,  True]])

#### Indexing within a matrix

In [52]:
a = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25],
    [26,27,28,29,30]
])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [53]:
a[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [50]:
a[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [55]:
a[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [58]:
b = np.array([[1,2],[6,7]])
print(b)

[[1 2]
 [6 7]]


In [60]:
c = a[0:2, 0:2]
print(c)

[[1 2]
 [6 7]]


In [61]:
c == b

array([[ True,  True],
       [ True,  True]])