In [1]:
import numpy as np

class Matrix:
    def __init__(self, matrix):
        self.matrix = np.array(matrix)
        self.dimensions = self.matrix.shape
        self.size = self.matrix.size
        self.rows, self.cols = self.dimensions
    # end __init__
    
    def find_first_index_in(self,matrix):
        if self.dimensions >= matrix.dimensions:
            return None
        else:
            for i in range(0,matrix.rows-self.rows+1):
                for j in range(0,matrix.cols-self.cols+1):
                    original_matrix_part = matrix.matrix[i:(i+self.rows), j:(j+self.cols)]
                    if np.array_equal(self.matrix, original_matrix_part):
                        return (i,j)
                    # end if
                # end for
            # end for
            return None
        # end if
    # end find_first_index_in
    
    def find_all_indices_in(self,matrix):
        coords = []
        if self.dimensions >= matrix.dimensions:
            return None
        else:
            for i in range(0,matrix.rows-self.rows+1):
                for j in range(0,matrix.cols-self.cols+1):
                    original_matrix_part = matrix.matrix[i:(i+self.rows), j:(j+self.cols)]
                    if np.array_equal(self.matrix, original_matrix_part):
                        coords.append((i,j))
                    # end if
                # end for
            # end for
            return coords if len(coords) > 0 else None
        # end if
    # end find_all_in
    
    def rotate_by_radians_in(self,matrix,rotation):
        rotated_matrix = self.matrix.copy()
        rotated_matrix = np.rot90(rotated_matrix, k=rotation*2)
        original_matrix = matrix.matrix.copy()
        indices = self.find_all_indices_in(matrix)
        if indices == None:
            return None
        else:
            for coords in indices:
                original_matrix[coords[0]:coords[0]+self.rows , coords[1]:coords[1]+self.cols] = rotated_matrix
            # end for
            return original_matrix
        # end if
    # end rotate_by_in
# end Matrix

In [2]:
matrix = Matrix([
    [1,2,3,9,9],
    [4,5,6,1,2],
    [7,8,9,4,5],
    [7,9,9,6,5],
    [4,1,2,7,8]
])

print(matrix.dimensions)

(5, 5)


In [3]:
# Matrix find first index of 2x2

matA = Matrix([
    [9,9],
    [1,2]
])

print(matA.find_first_index_in(matrix))

(0, 3)


In [4]:
# Matrix find all indices of 2x2

print(matA.find_all_indices_in(matrix))

[(0, 3), (3, 1)]


In [5]:
# Matrix find first index for 3x2

matB = Matrix([
    [8,9,4],
    [9,9,6]
])

print(matB.find_first_index_in(matrix))

(2, 1)


In [7]:
# Matrix Rotation

matC = Matrix([
    [1,2],
    [4,5]
])

rotation = 0.5
print(matC.rotate_by_radians_in(matrix,rotation))

[[2 5 3 9 9]
 [1 4 6 2 5]
 [7 8 9 1 4]
 [7 9 9 6 5]
 [4 1 2 7 8]]
